version: '3'

services:
  farm-manager-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_PASSWORD=postgresql
      - POSTGRESQL_DATABASE=farm-manager-db
